name: CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js
      uses: actions/setup-node@v2
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests
      run: npm test

    - name: Build project
      run: npm run build
  
    - name: Install AWS CDK
      run: npm install -g aws-cdk
    
    - name: Synthesize CloudFormation Template
      run: cdk synth
    
    - name: Generate difference report
      run: cdk diff || true
    
    - name: Deploy to AWS
      run: cdk deploy --require-approval never
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'ap-southeast-2'

