name: CI

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js
      uses: actions/setup-node@v2
    
    - name: Install dependencies
      run: npm ci

    - name: Install AWS CDK
      run: npm install -g aws-cdk
    
    - name: Run tests
      run: npm test
    
    - name: Build project
      run: npm run build
    
    - name: Synthesize CloudFormation Template
      run: cdk synth
    
    - name: Generate difference report
      run: cdk diff || true

